# Generated by Django 5.0.6 on 2024-05-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("category", models.CharField(max_length=100)),
                ("details", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="WeeklyStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("staff_name", models.CharField(max_length=100)),
                ("pizza_box", models.IntegerField()),
                ("cooking_oil", models.IntegerField()),
                ("salt", models.IntegerField()),
                ("sugar", models.IntegerField()),
                ("dishwashing_liquid", models.IntegerField()),
                ("bleach", models.IntegerField()),
                ("pine_gel", models.IntegerField()),
                ("black_bags", models.IntegerField()),
                ("hand_soap", models.IntegerField()),
                ("apron_washing_powder", models.IntegerField()),
                ("coke_zero", models.IntegerField()),
                ("coke", models.IntegerField()),
                ("fanta", models.IntegerField()),
                ("iced_tea_peach", models.IntegerField()),
                ("iced_tea_lemon", models.IntegerField()),
                ("still_water", models.IntegerField()),
                ("sparkling_water", models.IntegerField()),
                ("sprite", models.IntegerField()),
                ("heineken_zero", models.IntegerField()),
                ("savanna_zero", models.IntegerField()),
                ("flour_white", models.IntegerField()),
                ("paper_towel", models.IntegerField()),
                ("serviette", models.IntegerField()),
                ("straws", models.IntegerField()),
                ("foil", models.IntegerField()),
                ("clingwrap", models.IntegerField()),
                ("chilli", models.IntegerField()),
                ("garlic", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="InventoryItem",
        ),
    ]
