version: '3'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: pizza
      POSTGRES_USER: CParker
      POSTGRES_PASSWORD: P@ssw0rd!Secure123
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build: .
    command: gunicorn inventory_system.wsgi:application --bind 0.0.0.0:8080
    environment:
      DEBUG: 'True'
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
