version: '3.8'

services:
  web:
    build: .
    command: gunicorn inventory_system.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: inventory_system_db
      POSTGRES_USER: inventory_user
      POSTGRES_PASSWORD: securepassword

volumes:
  postgres_data:
  static_volume:
