# Generated by Django 5.0.6 on 2024-05-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PizzaOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("Uber", "Uber"),
                            ("Mr Delivery", "Mr Delivery"),
                            ("Bolt", "Bolt"),
                            ("Window", "Window"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "pizza_type",
                    models.JSONField(
                        help_text="A JSON object containing pizza types and their quantities"
                    ),
                ),
                ("extra_toppings", models.TextField(blank=True)),
                ("preparation_time", models.IntegerField(help_text="Time in minutes")),
                ("order_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
