# Generated by Django 5.0.6 on 2024-09-05 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("quantity", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Pizza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="PizzaOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("Uber", "Uber"),
                            ("Mr Delivery", "Mr Delivery"),
                            ("Bolt", "Bolt"),
                            ("Window", "Window"),
                            ("Other", "Other"),
                        ],
                        help_text="Platform used for ordering",
                        max_length=50,
                        verbose_name="Delivery Platform",
                    ),
                ),
                (
                    "extra_toppings",
                    models.TextField(
                        blank=True,
                        help_text="Any extra toppings requested by the customer",
                        verbose_name="Extra Toppings",
                    ),
                ),
                (
                    "preparation_time",
                    models.IntegerField(help_text="Time in minutes for preparation"),
                ),
                ("order_time", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "display",
                    models.BooleanField(
                        default=True,
                        help_text="Toggle whether the order should be visible on the order list",
                        verbose_name="Display Order",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PizzaIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_needed", models.FloatField(default=0)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.ingredient",
                    ),
                ),
                (
                    "pizza",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.pizza"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pizza",
            name="ingredients",
            field=models.ManyToManyField(
                through="orders.PizzaIngredient", to="orders.ingredient"
            ),
        ),
        migrations.CreateModel(
            name="PizzaOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.pizzaorder",
                    ),
                ),
                (
                    "pizza_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.pizza"
                    ),
                ),
            ],
            options={
                "ordering": ["pizza_type"],
            },
        ),
    ]
