# Generated by Django 5.0.6 on 2024-05-29 20:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("quantity", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Pizza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="PizzaOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("Uber", "Uber"),
                            ("Mr Delivery", "Mr Delivery"),
                            ("Bolt", "Bolt"),
                            ("Window", "Window"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("pizza_type", models.JSONField(default=list)),
                ("quantities", models.JSONField(default=list)),
                ("extra_toppings", models.TextField(blank=True)),
                ("preparation_time", models.IntegerField(help_text="Time in minutes")),
                ("order_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="PizzaIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_needed", models.FloatField(default=0)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.ingredient",
                    ),
                ),
                (
                    "pizza",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.pizza"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="pizza",
            name="ingredients",
            field=models.ManyToManyField(
                through="orders.PizzaIngredient", to="orders.ingredient"
            ),
        ),
    ]
