# Generated by Django 5.0.6 on 2024-05-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pizzaorder",
            name="pizza_type",
            field=models.JSONField(default=dict),
        ),
    ]
