# Generated by Django 5.0.6 on 2024-09-01 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_pizzaorder_display"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pizzaorder",
            name="pizza_type",
        ),
        migrations.RemoveField(
            model_name="pizzaorder",
            name="quantities",
        ),
        migrations.CreateModel(
            name="PizzaOrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.pizzaorder",
                    ),
                ),
                (
                    "pizza_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="orders.pizza"
                    ),
                ),
            ],
        ),
    ]
