# Generated by Django 5.0.6 on 2024-05-20 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_pizzaorder_pizza_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pizzaorder",
            name="pizza_type",
            field=models.JSONField(default=list),
        ),
    ]
