# Generated by Django 5.0.6 on 2024-05-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_pizzaorder_pizza_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="pizzaorder",
            name="quantities",
            field=models.JSONField(default=list),
        ),
    ]
